spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: sysportnov@gmail.com
    password: jepemzinknaipzjc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true